version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /home/daimaxiaofeng/apps/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
